### ISSUE TITLE
Mod support - All items with 'damage'

### ISSUE THREAD

**Issue by disconsented** [SimpleServer/SimpleServer#230]
Any mod that adds content like enhanceable items or ones that degrade cause an end of stream error, we need a permanent fix!

**Comment by kevinpeno** [comment]
Sounds like they are trying to alter the protocol, which SimpleServer cannot support. Can you provide links to the source of the mods causing your problems?

**Comment by disconsented** [comment]
It happens with any mod (industrial craft and red power are examples) carrying extra data, like damage or enchantments.

**Comment by disconsented** [comment]
http://i43.tinypic.com/r8ce1s.png

**Comment by bryanburke** [comment]
Whether or not any particular item is enchantable is not transmitted via the protocol, as far as I can tell. The only real "permanent fix" I can think of is to create a config file to be parsed by SimpleServer containing all item IDs and damage values of enchantable items, which might take a while to compile for any given mod. As far as degrading items and others with "extra data," @kevinpeno is correct in that SimpleServer cannot account for protocol changes handled internally by any given mod.

**Comment by kevinpeno** [comment]
I know we have a ticket or two open for the same-ish issue. The problem is the lack of flexibility in the MC protocol to support extensions. Hell, even a small change to any existing packet can bring any implementing server to it's knees. This is solved with a packet added in 1.1 however (http://wiki.vg/Protocol#Plugin\_message\_.280xFA.29) and once implemented by bukkit and mods this entire situation will become irrelevant. I think, because of this, it is time to remove all support for anything except the base protocol, open a ticket to ensure passthrough, and close these plugin related ones.

**Comment by bryanburke** [comment]
@kevinpeno I second this motion. The new Plugin Message packet is indeed 
a standardized method of mod communication and the first true piece of 
Mojang's upcoming official mod API.

**Comment by heapoutofspace** [comment]
The plugin message does not solve this problem at all. However, I'm currently working on a (little hacky) fix. I will try to push my work in the next 30 minutes and would appreciate any feedback.

**Comment by heapoutofspace** [comment]
The code is on a new branch called 'enchantable' (I forgot to mention the issue Id in the commit) and it would already help me if you try to run the `fei` command on the vanilla server. A good max ID for vanilla is 360.

**Comment by bryanburke** [comment]
Tested on vanilla server with max ID of 360: found 49 items. Might be easier to test/debug if you add a "fei list" command to list all items that were found.

**Comment by heapoutofspace** [comment]
49 is the correct number, the IDs are stored in simpleserver.dat

**Comment by Silwing** [comment]
Is there any progress on this? Or any way I can help to make some progress? I really would love to run SimpleServer on my modded server with IC2, BC etc.

**Comment by disconsented** [comment]
Hows this going?

**Comment by STEX20** [comment]
Is it possible to put "Enchantable" Items in a seperate config-file to make the Wrapper compatible to IC2, BC etc.?

I just tried building myself a version with the IC2 Item-Ids added to the ENCHANTABLE Array in StreamTunnel.java, but no success, maybe i overlooked something, but this was only the first (quick-hackish) try.

**Comment by heapoutofspace** [comment]
There's an experimental solution for this issue, if you're interested please visit us on IRC (irc.euirc.net#SimpleServer) or build the [enchantable branch](https://github.com/SimpleServer/SimpleServer/tree/enchantable) on your own. I will not officially release this fix since the problem will most likely be resolved with the 1.3 protocol rewrite.
