### ISSUE TITLE
Player heads (and some mobs) always face towards f:0 in multiplayer

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#244]
I have been having this issue on my server since Minecraft 1.2. If you switch to external view, your own head moves normally but other players, skeletons and spiders face south.

I tested this issue on another machine with a complete fresh install of SimpleServer 8.4.2 and minecraft_server 1.2.3. Originally thought it was just a bug in SMP but after fresh install, it seems it's SimpleServer causing the issue.

**Comment by Maggistro** [comment]
I also have that bug. Currently i try to find the issue in the source code. The thing is i dont know what has changed in the streaming format that is send by minecraft. I am also not familiar with the code. Any help would be appriciated.

**Comment by lucifer6642** [comment]
Alas, I'm not a coder, I just try to report faults as I find them. Good luck to you and anyone else who can help.

**Comment by Aest47** [comment]
im also having this issue. did a update today on it, with new bukkit and minecraft server as well.

**Comment by SeeJayEmm** [comment]
I am also experiencing this. It appears to also effect animals.

**Comment by Aest47** [comment]
it affects Citizens NPCs as well

**Comment by bluefeet** [comment]
Ya, been having this problem since 1.2 I think.  Bloody annoying when someone says "look at this!" and your looking at what their head is looking at, which of course is on backwards.  :(

**Comment by ginbot86** [comment]
I can confirm that this happens in 1.2.4 as well. Kinda makes your neck hurt when you see another player's head on backwards.

**Comment by heapoutofspace** [comment]
I think I fixed that with [this](https://github.com/SimpleServer/SimpleServer/commit/3b54cccaf8a4aa997442ae060a2cbc51aee2f9bb) commit.

**Comment by Maggistro** [comment]
worked for me. thx man

**Comment by lucifer6642** [comment]
Strangely, worked with 1.2.3 when I created a new map. On updating my live server, no difference.
Updating to 1.2.4 on my test server also stopped it working again.

Is anyone else still having problems or is it just me?

**Comment by bluefeet** [comment]
Working fine for me.

**Comment by lucifer6642** [comment]
A HUUUUUGE thank you to sadimusi for fixing the bug and also for the helpful email reply. Spent hours mucking about with Eclipse, tried the command line option instead and it worked perfectly.
